trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install packages'

- script: npm run lint
  displayName: 'Lint'

- script: npm run build
  displayName: 'Build'
